# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure subscription 1(a1b0ae65-267d-4df3-b5a3-6052e6964a71)'
    azureContainerRegistry: '{"loginServer":"testacrjwlee0208.azurecr.io", "id" : "/subscriptions/a1b0ae65-267d-4df3-b5a3-6052e6964a71/resourceGroups/TEST-ACR-01/providers/Microsoft.ContainerRegistry/registries/testacrjwlee0208"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Build services'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure subscription 1(a1b0ae65-267d-4df3-b5a3-6052e6964a71)'
    azureContainerRegistry: '{"loginServer":"testacrjwlee0208.azurecr.io", "id" : "/subscriptions/a1b0ae65-267d-4df3-b5a3-6052e6964a71/resourceGroups/TEST-ACR-01/providers/Microsoft.ContainerRegistry/registries/testacrjwlee0208"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Push services'
    includeLatestTag: true
- task: AzureVmssDeployment@0
  inputs:
    azureSubscription: 'Azure subscription 1(a1b0ae65-267d-4df3-b5a3-6052e6964a71)'
    action: 'Update image'
    vmssName: 'TEST-VMSS-01'
    vmssOsType: 'Linux'
    imageUrl: 'testacrjwlee0208.azurecr.io/testacrjwlee0208/test_pipeline_build'
    customScriptsStorageAccount: 'cs110037ffeadff49cd'